name: generate-first-issues

on:
  pull_request: []
  schedule:
    # Run every night
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Generate First Issues
      uses: rseng/awesome-rseng@ff385e1f162f0c395f59f1123fb2f17935d6496b
      with:
        repos-file: '.github/repos.txt'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        export BRANCH_FROM="update/update-first-issues-$(date '+%Y-%m-%d')"
        git checkout -b ${BRANCH_FROM}
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add docs/*
        git commit -m "Automated deployment to update first issues $(date '+%Y-%m-%d')" --allow-empty
        git push origin ${BRANCH_FROM}
    - name: Open pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
        export BRANCH_FROM="update/update-first-issues-$(date '+%Y-%m-%d')"
        wget https://raw.githubusercontent.com/USRSE/usrse.github.io/71ae72c2a5524c502e0bb51c5ca764dd854eea18/scripts/pull-request.sh
          chmod +x ./pull-request.sh
          /bin/bash ./pull-request.sh
